# The URL the site will be built for
base_url = "https://cloudsal.at"

# The site title and description; used in feeds by default.
title = "Cloudsalat"
description = "Julian's website"

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Output directory for GitHub pages
output_dir = "github-pages"

# Configure RSS feed generation
generate_feeds = true
feed_filenames = ["rss.xml"]
feed_limit = 10

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "gruvbox-dark"

# Enable emoji rendering, e.g. from :smile:
render_emoji = true

[extra]
# Put all your custom variables here
