# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@v2
        with:
          tool: zola
      - uses: actions/checkout@v4
      - run: zola build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: github-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/deploy-pages@v4
