# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: zola build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: github-pages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
